backend:
  name: github
  repo: sidskaka/fullStack-ProjectM1
  branch: master

media_folder: static/assets
public_folder: /assets

collections: 
  - name: product
    label: Produit
    folder: products
    create: true
    fields: 
      - { name: title, required: true, label: Titre }
      - { name: price, required: true, label: Prix }
      - { name: description, required: true, label: Description, widget: markdown }
      - { name: image, required: true, label: Image, widget: image }
      - { name: couleur, required: true, label: Couleur }
      - { name: taille, required: true, label: Taille }
      - { name: categorie, required: true, label: Categorie }
      - { name: sku, required: false, label: Sku}
      - { name: path, required: false, label: Path }
  - name: categorie
    label: Categorie
    folder: categories
    create: true
    fields: 
      - { name: title, required: true, label: Titre }
      - { name: description, required: true, label: Description, widget: markdown }
      - { name: sku, required: false, label: Sku}
      - { name: path, required: true, label: Path }
  - name: blog
    label: blog
    folder: blogs
    create: true
    fields:
      - { name: title, required: true, label: Title }
      - { name: resume, required: true, label: Resume }
      - { name: textcomplet, required: true, label: Textcomplet, widget: markdown }
      - { name: image, required: true, label: image, widget: image }
      - { name: path, required: true, label: Path }
      - { name: date, required: true, label: Date, widget: date }
  # - name: markdown
  #   label: markdown
  #   folder: src/markdown-pages
  #   create: true
  #   fields:
  #     - { name: slug, required: true, label: Slug }
  #     - { name: title, required: true, label: Title }
  #     - { name: date, required: true, label: Date, widget: date }